import PageHeader from "@/components/PageHeader";

export const metadata = {
  title: "Terms & Conditions",
  description: "Terms and Conditions for using StudyCalc's free academic calculators.",
  alternates: {
    canonical: "https://www.studycalc.co/terms",
  },
};

export default function TermsPage() {
  return (
    <main className="max-w-5xl mx-auto px-6 py-20">

      <PageHeader
        title="Terms & Conditions"
        description="Please read these terms before using StudyCalc."
      />

      <div className="mt-16 rounded-2xl border border-slate-800 bg-slate-900 p-8 space-y-8">

        <section>
          <h2 className="text-2xl font-bold">
            Acceptance of Terms
          </h2>

          <p className="mt-4 text-slate-300 leading-8">
            By using StudyCalc, you agree to these Terms and Conditions.
            If you do not agree, please discontinue using the website.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-bold">
            Calculator Accuracy
          </h2>

          <p className="mt-4 text-slate-300 leading-8">
            We strive to provide accurate calculations, but results should
            always be verified before making academic or financial decisions.
            Grading scales and academic policies vary between institutions,
            and StudyCalc&apos;s calculators are built on commonly used
            standards that may not exactly match your school&apos;s official
            policy.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-bold">
            Limitation of Liability
          </h2>

          <p className="mt-4 text-slate-300 leading-8">
            StudyCalc is provided &quot;as is&quot; without warranties of any
            kind. We are not liable for any loss, damage, or academic
            consequence arising from the use of, or reliance on, results
            generated by our calculators. You are responsible for verifying
            any calculation that affects your academic standing.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-bold">
            Intellectual Property
          </h2>

          <p className="mt-4 text-slate-300 leading-8">
            The StudyCalc name, design, and original written content are the
            property of StudyCalc. You may use the calculators for personal,
            non-commercial purposes. Reproducing or redistributing our
            articles or tools without permission is not permitted.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-bold">
            Acceptable Use
          </h2>

          <p className="mt-4 text-slate-300 leading-8">
            You agree not to misuse the site — including attempting to
            disrupt its operation, scrape it at scale, or use it in any way
            that violates applicable law.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-bold">
            Changes
          </h2>

          <p className="mt-4 text-slate-300 leading-8">
            We may update these terms at any time to improve our services.
            Continued use of StudyCalc after changes are posted constitutes
            acceptance of the revised terms.
          </p>
        </section>

      </div>

    </main>
  );
}
