import PageHeader from "@/components/PageHeader";

export default function DisclaimerPage() {
  return (
    <main className="min-h-screen bg-slate-950 text-white">
      <div className="max-w-4xl mx-auto px-6 py-16">
        
        <PageHeader 
          title="Disclaimer" 
          description="Last updated: 2026" 
        />

        <div className="mt-12 rounded-2xl border border-slate-800 bg-slate-900 p-8 md:p-10 space-y-6 text-slate-300 leading-relaxed">
          
          <p>
            StudyCalc is provided for educational and informational purposes only. The calculators and tools available on this website are designed to assist students with academic estimations.
          </p>

          <p>
            While we strive to provide highly accurate calculations, we cannot guarantee that all results are error-free or fully up-to-date. Grading policies and GPA scales can vary significantly between different schools, colleges, and universities.
          </p>

          <p>
            Users should always verify important academic or financial calculations (such as final graduation requirements or official GPAs) directly with their respective educational institutions, advisors, or official handbooks.
          </p>

          <p>
            By using StudyCalc, you agree that we are not responsible or liable for any academic, financial, or personal decisions made based on the results generated by our tools.
          </p>

          <p className="pt-4 border-t border-slate-800 text-slate-400">
            If you find any issues, errors, or discrepancies with our calculators, please reach out to us via our{" "}
            <a href="/contact" className="text-cyan-400 hover:underline">
              Contact Page
            </a>.
          </p>

        </div>
      </div>
    </main>
  );
}